[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "vs_liif"
version = "1.2.0"
description = "AI resizing for VapourSynth using LIIF. Upscaling and downscaling."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "pifroggi" }]
license = "BSD-3-Clause"
license-files = ["LICENSE"]

keywords = [
	"vapoursynth",
	"video",
	"resize",
	"resizing",
	"liif",
	"filtering"
]

classifiers = [
	"Programming Language :: Python :: 3",
	"Topic :: Multimedia :: Video",
    "Environment :: GPU",
]

dependencies = [
	"vapoursynth",
	"numpy",
]

[project.urls]
Homepage = "https://github.com/pifroggi/vs_liif"
Repository = "https://github.com/pifroggi/vs_liif"
Issues = "https://github.com/pifroggi/vs_liif/issues"
